no_progress = true
format = "markdown"
output = "report.md"
accept = ["200", "429"]
scheme = ["https", "http"]
skip_missing = false
include_verbatim = false
exclude = [
    'https://invisible.forgejo.org/forgejo/runner',
    'https://code.forgejo.org/api/v1',
    'https://codeberg.org/forgejo/forgejo/vX.Y/forgejo',
    'https://dash\.cloudflare\.com/\?to\=/\:account/turnstile',
    'https://img.shields.io/badge/%7B%7B.label%7D%7D-%7B%7B.text%7D%7D-%7B%7B.color%7D%7D',
]
exclude_all_private = true
