name: Links

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  linkChecker:
    runs-on: docker
    steps:
      - name: Checkout next
        uses: actions/checkout@v6
        with:
          ref: next
          path: next

      - name: Checkout v11.0
        uses: actions/checkout@v6
        with:
          ref: v11.0
          path: v11.0

      - name: Install lychee
        run: |
          curl -sL -o lychee.tar.gz "https://github.com/lycheeverse/lychee/releases/download/lychee-v0.22.0/lychee-x86_64-unknown-linux-gnu.tar.gz"
          echo d004215a789db155779d3263e6e18ad424879b18eeddb00745efb8d9b2bd8891 lychee.tar.gz | sha256sum -c && tar -xzf lychee.tar.gz

      - name: Check links
        id: lychee
        run: ./lychee --config next/.lychee.toml next/docs v11.0/docs
        continue-on-error: true

      - name: Postprocess
        run: sed -E "s+(### Errors in )(.*)+\1[\2](https://codeberg.org/forgejo/docs/src/branch/\2)+" -i ./report.md

      - name: Update issue
        uses: https://data.forgejo.org/peter-evans/create-issue-from-file@v5.0.1
        with:
          title: Dead links report
          issue-number: 583
          content-filepath: ./report.md
