name: Links

on:
  schedule:
    - cron: '00 18 * * *'
jobs:
  linkChecker:
    runs-on: docker
    steps:
      - name: Checkout next
        uses: actions/checkout@v4

      - name: Checkout v7
        uses: actions/checkout@v4
        with:
          path: v7

      - name: Install lychee
        run: |
          curl -sLO "https://github.com/lycheeverse/lychee/releases/download/lychee-v0.18.0/lychee-x86_64-unknown-linux-gnu.tar.gz"
          tar -xvzf "lychee-x86_64-unknown-linux-gnu.tar.gz"

      - name: Link Checker
        id: lychee
        run: ./lychee --config .lychee.toml docs v7/docs

      - name: Update issue
        if: '!cancelled()'
        uses: https://github.com/peter-evans/create-issue-from-file@v5.0.0
        with:
          title: Dead links report
          issue-number: 583
          content-filepath: ./report.md
