name: Links

on:
  schedule:
    - cron: '0 18 * * *'
jobs:
  linkChecker:
    runs-on: docker
    steps:
      - name: Checkout next
        uses: actions/checkout@v4
        with:
          ref: next
          path: next

      - name: Checkout v11.0
        uses: actions/checkout@v4
        with:
          ref: v11.0
          path: v11.0

      - name: Install lychee
        run: |
          curl -sLO "https://github.com/lycheeverse/lychee/releases/download/lychee-v0.18.1/lychee-x86_64-unknown-linux-gnu.tar.gz"
          tar -xvzf "lychee-x86_64-unknown-linux-gnu.tar.gz"

      - name: Check links
        id: lychee
        run: ./lychee --config .lychee.toml next/docs v11.0/docs
        continue-on-error: true

      - name: Postprocess
        run: sed -E "s+(### Errors in )(.*)+\1[\2](https://codeberg.org/forgejo/docs/src/branch/\2)+" -i ./report.md

      - name: Update issue
        uses: https://github.com/peter-evans/create-issue-from-file@v5.0.0
        with:
          title: Dead links report
          issue-number: 583
          content-filepath: ./report.md
