name: pr

on:
  pull_request_target:

jobs:
  preview:
    runs-on: docker
    container:
      image: data.forgejo.org/oci/ci:1
    steps:
      - uses: https://data.forgejo.org/actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: lint
        env:
          GITHUB_TOKEN: override
          FORGEJO_TOKEN: override
        run: |
          npm install -g corepack@latest
          corepack enable
          pnpm install --frozen-lockfile
          pnpm run lint:remark
          pnpm run format:prettier
          git diff --exit-code
      - name: run typos
        uses: https://github.com/crate-ci/typos@v1.29.4
        with:
          write_changes: true
      - name: check typos result
        env:
          GITHUB_TOKEN: override
          FORGEJO_TOKEN: override
        run: 'git diff --exit-code --word-diff || ( echo "Hint: Fix misspelled words or add false positives in .typos.toml" && false )'
      - name: scripts/cli-docs.sh
        env:
          GITHUB_TOKEN: override
          FORGEJO_TOKEN: override
        run: |
          scripts/cli-docs.sh run ${{ env.GITHUB_BASE_REF }} > docs/admin/command-line.md
          git diff --exit-code
      - name: release-schedule
        env:
          GITHUB_TOKEN: override
          FORGEJO_TOKEN: override
        run: |
          pnpm run update-schedule
          git diff --exit-code || (echo "Error: Run 'pnpm run update-schedule' to generate the markdown release schedule and commit it" && false)
      - name: get forgejo.org and move the docs
        env:
          GITHUB_TOKEN: override
          FORGEJO_TOKEN: override
        run: |
          git clone --recursive --depth 1 https://codeberg.org/forgejo/website/ /tmp/website
          apt-get update -qq && apt-get install -qq -y rsync
          rsync -av --delete ./ /tmp/website/forgejo-docs/${{ env.GITHUB_BASE_REF }}/
      - name: install
        env:
          GITHUB_TOKEN: override
          FORGEJO_TOKEN: override
        run: |
          cd /tmp/website
          corepack enable
          pnpm install --frozen-lockfile
      - name: build
        env:
          GITHUB_TOKEN: override
          FORGEJO_TOKEN: override
        run: |
          cd /tmp/website
          colon=':'
          branch=docs_pull_${{ github.event.pull_request.number }}
          sed -i.orig -e "s|origin$colon '.*|origin$colon 'https$colon//forgejo.codeberg.page',|" -e "s|basePathname$colon '/'|basePathname$colon '/@$branch//'|" src/config.ts
          cat src/config.ts
          corepack enable
          pnpm run build
          mv dist /tmp
      - name: preview
        if: ${{ secrets.WEBSITETOKEN != '' }}
        uses: https://data.forgejo.org/forgejo/action-website-preview@main
        with:
          directory: /tmp/dist
          name: 'docs_pull_${{ github.event.pull_request.number }}'
          pages-token: ${{ secrets.WEBSITETOKEN }}
          repository: forgejo/docs
          repository-host: codeberg.org
          repository-token: ${{ secrets.WEBSITETOKEN }}
          pr-number: ${{ github.event.pull_request.number }}
